# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CleanMVVMRxAppStore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CleanMVVMRxAppStore

pod 'RxSwift'
pod 'RxCocoa'

  target 'CleanMVVMRxAppStoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CleanMVVMRxAppStoreUITests' do
    # Pods for testing
  end

end
